name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    run-on: ubuntu-latest
    timout-minutes: 30

    steps:
      - name: BuildProd
        run: ./scripts/buildprod.sh





